.gitignore
backend/.gitignore
backend/HELP.md
backend/mvnw
backend/mvnw.cmd
backend/pom.xml
backend/src/main/java/com/capstone/studentplacementplatform/StudentplacementplatformApplication.java
backend/src/main/resources/application.properties
backend/src/test/java/com/capstone/studentplacementplatform/StudentplacementplatformApplicationTests.java

This takes care of setting up the initial repository structure and configuring the base of the backend using Spring Boot Initializer.

CONFIG: Adding initial repo structure for backend

---

.gitignore
backend/delivery/Dockerfile
backend/delivery/Jenkinsfile
backend/pom.xml

This PR takes care of adding a **delivery/** directory under the backend directory which includes a Dockerfile and a Jenkinsfile which will be used to build the backend Spring Boot app using OpenJDK17 and Ubuntu Focal as the base.

CONFIG: Adding Dockerfile and Jenkinsfile for building backend

---

backend/delivery/Jenkinsfile

This adjusts the artifact path for archiving .JAR files.

CONFIG: Adjusting artifact path

---

.gitignore
backend/pom.xml
backend/src/main/resources/application.properties

This PR includes the initial configuration of the User on the backend. It also adds dependencies required for interacting with the MySQL database and connecting to it. The DB_ROOT_PASSWORD environment variable is used as we should not store the password in plain-text for security purposes - this variable will be set on the host machine and consumed this way.

FEATURE: Starting initial User configuration and database connection

---

backend/delivery/Jenkinsfile

This takes care of adding a stage to actually deploy the backend container to the EC2 instance.

DELIVERY: Adding stage to deploy backend

---

backend/delivery/Dockerfile
backend/delivery/Jenkinsfile

This PR takes care of setting the DB_ROOT_PASSWORD var using the Jenkins credential / secret. This will allow the backend to connect to the database successfully.

DELIVERY: Setting DB_ROOT_PASSWORD var on image

---

.gitignore
backend/.gitignore
backend/pom.xml
backend/src/main/java/com/capstone/studentplacementplatform/controller/UserController.java
backend/src/main/java/com/capstone/studentplacementplatform/dto/RegistrationRequest.java
backend/src/main/java/com/capstone/studentplacementplatform/model/User.java
backend/src/main/java/com/capstone/studentplacementplatform/repository/UserRepository.java
backend/src/main/java/com/capstone/studentplacementplatform/service/UserService.java
backend/src/main/java/com/capstone/studentplacementplatform/validation/ValidRole.java
backend/src/main/java/com/capstone/studentplacementplatform/validation/ValidRoleValidator.java
backend/src/main/resources/application.properties

This pull request takes care of creating a new POST endpoint at **/api/users/registration**. This takes username, password, email, firstname, lastname, and role and creates a new user in the database.
Validation is done to ensure:
- email isn't already being used
- username isn't already being used
- and that the role passed is one of 'Student', 'Placement Officer, or 'Recruiter'

FEATURE: Adding User Registration API

---

backend/pom.xml
backend/src/main/java/com/capstone/studentplacementplatform/controller/UserController.java
backend/src/main/java/com/capstone/studentplacementplatform/dto/LoginRequest.java
backend/src/main/java/com/capstone/studentplacementplatform/repository/UserRepository.java
backend/src/main/java/com/capstone/studentplacementplatform/security/SecurityConfig.java
backend/src/main/java/com/capstone/studentplacementplatform/service/UserService.java
backend/src/main/java/com/capstone/studentplacementplatform/validation/ValidRole.java
backend/src/main/java/com/capstone/studentplacementplatform/validation/ValidRoleValidator.java
backend/src/main/resources/application.properties

This PR takes care of adding support for:
- hashing user passwords during the registration process at **/api/users/register**.
- adding a new login endpoint at **/api/users/auth** which vaildates username and hashed password against what is stored in the MySQL database.
- adding some basic security config in addition with the Spring Boot Security dependency.

FEATURE: Addition of '/auth' endpoint

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/UserController.java

Include userId in auth success message

FEATURE: Include userId in auth success message

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/UserController.java
backend/src/main/java/com/capstone/studentplacementplatform/repository/UserRepository.java
backend/src/main/java/com/capstone/studentplacementplatform/service/UserService.java

This takes care of adding a new endpoint for **/api/users/{id}** which allows you to fetch information about a user with their ID. User password is REDACTED in the response.

FEATURE: Add endpoint to fetch user details by ID

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/SkillController.java
backend/src/main/java/com/capstone/studentplacementplatform/model/Skill.java
backend/src/main/java/com/capstone/studentplacementplatform/repository/SkillRepository.java
backend/src/main/java/com/capstone/studentplacementplatform/service/SkillService.java

This takes care of adding 5 new endpoints for skills:
- [GET] > /api/skills/{id}: Retrieves a skill by its unique identifier.
- [GET] > /api/skills/user/{userId}: Retrieves all skills associated with a specific user.
- [POST] > /api/skills/user/{userId}: Adds a new skill for a specified user.
- [PUT] > /api/skills/{id}: Updates an existing skill.
- [DELETE] > /api/skills/{id}: Deletes a skill by its unique identifier.

FEATURE: Adding five 'Skills' endpoints

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/EducationHistoryController.java
backend/src/main/java/com/capstone/studentplacementplatform/controller/SkillController.java
backend/src/main/java/com/capstone/studentplacementplatform/model/EducationHistory.java
backend/src/main/java/com/capstone/studentplacementplatform/model/Skill.java
backend/src/main/java/com/capstone/studentplacementplatform/repository/EducationHistoryRepository.java
backend/src/main/java/com/capstone/studentplacementplatform/repository/SkillRepository.java
backend/src/main/java/com/capstone/studentplacementplatform/service/EducationHistoryService.java
backend/src/main/java/com/capstone/studentplacementplatform/service/SkillService.java

This takes care of adding a new EducationHistory and Skill service.
**EducationHistory**
- **[GET] > /api/education/{id}**: Retrieves education history by its unique identifier.
- **[GET] > /api/education/user/{userId}**: Retrieves all education history associated with a specific user.
- **[POST] > /api/education**: Adds a new education history entry.
- **[PUT] > /api/education/{id}**: Updates an existing education history entry.
- **[DELETE] > /api/education/{id}**: Deletes an education history entry by its unique identifier.
**Skills**
- **[GET] > /api/skills/{id}**: Retrieves a skill by its unique identifier.
- **[GET] > /api/skills/user/{userId}**: Retrieves all skills associated with a specific user.
- **[POST] > /api/skills/user/{userId}**: Adds a new skill for a specified user.
- …

FEATURE: Adding new EducationHistory and Skills services

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/CompanyController.java
backend/src/main/java/com/capstone/studentplacementplatform/dto/LoginRequest.java
backend/src/main/java/com/capstone/studentplacementplatform/model/Company.java
backend/src/main/java/com/capstone/studentplacementplatform/repository/CompanyRepository.java
backend/src/main/java/com/capstone/studentplacementplatform/service/CompanyService.java

This PR takes care of adding 5 new company endpoints to the new company service.
- **[POST] > /api/companies:** Adds a new company entry.
- **[GET] > /api/companies/{id}:** Retrieves a company by its unique identifier.
- **[GET] > /api/companies:** Retrieves all companies.
- **[PUT] > /api/companies/{id}:** Updates an existing company.
- **[DELETE] > /api/companies/{id}:** Deletes a company by its unique identifier.

FEATURE: Adding 5 new 'Company' endpoints

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/EducationHistoryController.java
backend/src/main/java/com/capstone/studentplacementplatform/dto/EducationHistoryRequest.java
backend/src/main/java/com/capstone/studentplacementplatform/model/Skill.java
backend/src/main/java/com/capstone/studentplacementplatform/model/User.java
backend/src/main/java/com/capstone/studentplacementplatform/repository/EducationHistoryRepository.java
backend/src/main/java/com/capstone/studentplacementplatform/service/EducationHistoryService.java
backend/src/main/java/com/capstone/studentplacementplatform/service/SkillService.java

This takes care of adding a new education history service. It also adjusts existing logic in other services to ensure foreign keys are correctly associated with the user ID in the 'users' table.

FEATURE: Add education history service and adjust foreign keys

---

backend/src/main/java/com/capstone/studentplacementplatform/dto/LoginRequest.java
backend/src/main/java/com/capstone/studentplacementplatform/dto/RegistrationRequest.java
backend/src/test/java/com/capstone/studentplacementplatform/controller/UserControllerTest.java

This PR takes care of adding 3 unit tests for the User Controller.
- **testGetUserById_Success**
- **testRegisterUser_Success**
- **testDeleteSkill_Success**

TESTING: Adding unit testing for User Controller

---

database/Jenkinsfile

This PR takes care of adding a new Jenkins stage in order to create the required database on the MySQL container / database server - **student_placement_platform**

DELIVERY: Adding stage to create DB on MySQL container

---

backend/delivery/Dockerfile
backend/src/main/resources/application.properties
scripts/mac/run.sh
scripts/mac/stop.sh
scripts/windows/run.bat
scripts/windows/stop.bat

This includes a **run.sh** and **stop.sh** script for Mac to use for local development and the same in the form of **.bat** files for Windows.

1SCRIPTS: Configuring Mac and Windows script for local dev

---

frontend/delivery/Dockerfile
frontend/delivery/Jenkinsfile

This PR takes care of adding a Dockerfile and Jenkinsfile for the frontend React app.

DELIVERY: Adding Dockerfile for the frontend

---

scripts/mac/run.sh
scripts/mac/stop.sh
scripts/windows/run.bat
scripts/windows/stop.bat

This takes care of updating the scripts for local dev to cover the addition of building and running the React frontend.

SCRIPTS: Adding frontend build to local dev scripts

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/CompanyController.java
backend/src/main/java/com/capstone/studentplacementplatform/controller/UserController.java
frontend/student-placement-platform/src/pages/HomePage.tsx
frontend/student-placement-platform/src/pages/SignUpPage.tsx

linked home page register button to the registration page
changed registration page values to map to expected database values, changed header to "register" from "log in"

FEATURE: changes to home page and registration page

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/InternshipController.java
backend/src/main/java/com/capstone/studentplacementplatform/model/Company.java
backend/src/main/java/com/capstone/studentplacementplatform/model/Internship.java
backend/src/main/java/com/capstone/studentplacementplatform/repository/InternshipRepository.java
backend/src/main/java/com/capstone/studentplacementplatform/service/InternshipService.java
backend/src/main/resources/application.properties

This takes care of adding support for a new internship listing service. It supports CRUD operations - the scheme / DB structure for this table likely needs to be normalized and improved on but this can be tacked in a further pull request.

FEATURE: Adding support for internship listing

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/UserController.java
backend/src/main/java/com/capstone/studentplacementplatform/service/UserService.java

This adds a new PUT endpoint to allow for updates to existing user data.

FEATURE: Adding PUT endpoint to allow user data updates

---

backend/src/main/java/com/capstone/studentplacementplatform/security/SecurityConfig.java

Disable CORS on the backend APIs

SECURITY: Disable CORS to allow frontend requests

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/UserController.java

Include the user role in response to frontend auth request.

FEATURE: Include role in response for login

---

frontend/student-placement-platform/src/RootComponent.tsx
frontend/student-placement-platform/src/pages/Login.tsx
frontend/student-placement-platform/src/resources/routes-constants.ts

Save User ID and role to storage on login.

FEATURE: Save user role and ID to local storage

---

frontend/student-placement-platform/package-lock.json
frontend/student-placement-platform/src/App.tsx
frontend/student-placement-platform/src/RootComponent.tsx
frontend/student-placement-platform/src/components/AuthenticatedNavbar.tsx
frontend/student-placement-platform/src/components/UnauthenticatedNavbar.tsx
frontend/student-placement-platform/src/pages/Dashboard.tsx
frontend/student-placement-platform/src/pages/HomePage.tsx
frontend/student-placement-platform/src/pages/Login.tsx
frontend/student-placement-platform/src/pages/Register.tsx
frontend/student-placement-platform/src/styles/index.css

Add home dashboard and direct users here on login

FEATURE: Add home dashboard and direct on login

---

frontend/student-placement-platform/src/RootComponent.tsx
frontend/student-placement-platform/src/components/AuthenticatedNavbar.tsx
frontend/student-placement-platform/src/resources/routes-constants.ts

Adjust navbar based on the user role

FEATURE: Adjust redirect for student profile in navbar

---

backend/src/main/java/com/capstone/studentplacementplatform/model/Internship.java
frontend/student-placement-platform/src/pages/Dashboard.tsx

Changing backend fetch type to EAGER for internships and adding display for job listings.

FEATURE: Adding display for internship listings

---

frontend/student-placement-platform/src/RootComponent.tsx
frontend/student-placement-platform/src/pages/Dashboard.tsx
frontend/student-placement-platform/src/pages/InternshipDetail.tsx
frontend/student-placement-platform/src/styles/index.css
scripts/mac/create-dummy-data.sh
scripts/windows/create-dummy-data.sh

This adds support for viewing an internship position on the frontend and also adds scripts for creating dummy data e.g. users, companies, internships, etc. via Curl for Bash and invoke web request for Windows.

FEATURE: Add support for viewing internships positions

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/UserController.java
frontend/student-placement-platform/package-lock.json
frontend/student-placement-platform/package.json
frontend/student-placement-platform/src/components/AuthenticatedNavbar.tsx
frontend/student-placement-platform/src/pages/Login.tsx
frontend/student-placement-platform/src/pages/Register.tsx

Include username and role in the navbar with dropdown for profile and logout options.

FEATURE: Username in navbar with dropdown

---

frontend/student-placement-platform/src/components/AuthenticatedNavbar.tsx
frontend/student-placement-platform/src/pages/Dashboard.tsx
frontend/student-placement-platform/tsconfig.json

Add support for searching by company and location on the internship listings page.

FEATURE: Add support for search by Company and Location

---

frontend/student-placement-platform/src/RootComponent.tsx
frontend/student-placement-platform/src/components/AuthenticatedNavbar.tsx
frontend/student-placement-platform/src/pages/Account.tsx
frontend/student-placement-platform/src/pages/AddEducationHistory.tsx
frontend/student-placement-platform/src/pages/Dashboard.tsx
frontend/student-placement-platform/src/pages/StudentProfile.tsx
frontend/student-placement-platform/src/styles/index.css

Split user account and profile options and provide access via navbar dropdown

FEATURE: Split account and profile with navbar options

---

backend/src/main/java/com/capstone/studentplacementplatform/controller/UserController.java
frontend/student-placement-platform/src/pages/Account.tsx

Currently the first name and lastname is not saved on a PUT request to update user details, this fixes that.

FEATURE: Correctly save fname and lname in user PUT

---

frontend/student-placement-platform/src/RootComponent.tsx

re added home page to root component

---

vitest.config.ts

added config for tests
